import gamepad from "./assets/gamepad.png";
import keyboard from "./assets/keyboard.png";
import monitor from "./assets/monitor.png";
import chair from "./assets/chair.png";
import coat from "./assets/coat.png";
import bookshelf from "./assets/bookshelf.png";
import buffledog from "./assets/dufflebag.png";
import cloth1 from "./assets/clothing 1.png";
import cloth2 from "./assets/clothing 2.png";
import cloth3 from "./assets/clothing 3.png";
import cloth4 from "./assets/clothing 4.png";
import cloth5 from "./assets/clothing 5.png";
import cloth6 from "./assets/clothing 6.png";
import cloth7 from "./assets/clothing 7.png";
import cloth8 from "./assets/clothing 8.png";
import cloth9 from "./assets/clothing 9.png";
import shoe1 from "./assets/shoe1.png"
import dogfood from "./assets/dogfood.png";
import laptop from "./assets/laptop.png";
import camera from "./assets/camera.png";
import creame from "./assets/creame.png";
import car from "./assets/car.png";
import shoes from "./assets/shoes.png";
import gamepad2 from "./assets/gampad2.png";
import jacket from "./assets/jacket.png";
import graphiccard from "./assets/graphic card.webp";
import microphone from "./assets/microphone.webp";
import vrheadset from "./assets/vrheadset.webp";
import gamingrouter from "./assets/gamingrouter.png";
// export const allProducts = [
//   {
//     id: 1,
//     name: "HAVIT HV-G92 Gamepad",
//     image: gamepad,
//     discount: "40",
//     price: 120,
//     originalPrice: 160,
//     rating: 5,
//     reviews: 88,
//   },
//   {
//     id: 2,
//     name: "AK-900 Wired Keyboard",
//     image: keyboard,
//     discount: "35",
//     price: 960,
//     originalPrice: 1160,
//     rating: 4,
//     reviews: 75,
//   },
//   {
//     id: 3,
//     name: "IPS LCD Gaming Monitor",
//     image: monitor,
//     discount: "30",
//     price: 370,
//     originalPrice: 400,
//     rating: 5,
//     reviews: 99,
//   },
//   {
//     id: 4,
//     name: "S-Series Comfort Chair",
//     image: chair,
//     discount: "25",
//     price: 375,
//     originalPrice: 400,
//     rating: 4,
//     reviews: 99,
//   },
//   //   {
//   //     id: 5,
//   //     name: "HAVIT HV-G92 Gamepad",
//   //     image: gamepad,
//   //     discount: "-40%",
//   //     price: 120,
//   //     originalPrice: 160,
//   //     rating: 5,
//   //     reviews: 88,
//   //   },
//   //   {
//   //     id: 6,
//   //     name: "AK-900 Wired Keyboard",
//   //     image: keyboard,
//   //     discount: "-35%",
//   //     price: 960,
//   //     originalPrice: 1160,
//   //     rating: 4,
//   //     reviews: 75,
//   //   },
//   //   {
//   //     id: 7,
//   //     name: "IPS LCD Gaming Monitor",
//   //     image: monitor,
//   //     discount: "-30%",
//   //     price: 370,
//   //     originalPrice: 400,
//   //     rating: 5,
//   //     reviews: 99,
//   //   },
//   //   {
//   //     id: 8,
//   //     name: "S-Series Comfort Chair",
//   //     image: chair,
//   //     discount: "-25%",
//   //     price: 375,
//   //     originalPrice: 400,
//   //     rating: 4,
//   //     reviews: 99,
//   //   },
//   // ... add all your products from FlashSale
// ];

// export const products = [
//     {
//       id: 1,
//       name: "The north coat",
//       image: coat,
//       currentPrice: 260,
//       originalPrice: 360,
//       rating: 5,
//       reviews: 65,
//     },
//     {
//       id: 2,
//       name: "Gucci duffle bag",
//       image: buffledog,
//       currentPrice: 960,
//       originalPrice: 1160,
//       rating: 4.5,
//       reviews: 65,
//     },
//     {
//       id: 3,
//       name: "Small BookSelf",
//       image: bookshelf,
//       currentPrice: 360,
//       originalPrice: null,
//       rating: 5,
//       reviews: 65,
//     },
//     {
//       id: 4,
//       name: "The north coat",
//       image: cloth1,
//       currentPrice: 260,
//       originalPrice: 360,
//       rating: 5,
//       reviews: 65,
//     },
//     {
//       id: 5,
//       name: "Gucci duffle bag",
//       image: cloth2,
//       currentPrice: 960,
//       originalPrice: 1160,
//       rating: 4.5,
//       reviews: 65,
//     },
//     {
//       id: 6,
//       name: "Small BookSelf",
//       image: cloth3,
//       currentPrice: 360,
//       originalPrice: null,
//       rating: 5,
//       reviews: 65,
//     },
//     {
//       id: 7,
//       name: "The north coat",
//       image: cloth4,
//       currentPrice: 260,
//       originalPrice: 360,
//       rating: 5,
//       reviews: 65,
//     },
//     {
//       id: 8,
//       name: "Gucci duffle bag",
//       image: cloth5,
//       currentPrice: 960,
//       originalPrice: 1160,
//       rating: 4.5,
//       reviews: 65,
//     },
//     {
//       id: 9,
//       name: "Small BookSelf",
//       image: cloth6,
//       currentPrice: 360,
//       originalPrice: null,
//       rating: 5,
//       reviews: 65,
//     },

// ]

export  const allProducts = [
    {
      id: 1,
      name: "HAVIT HV-G92 Gamepad",
      image: gamepad,
      discount: "-40%",
      price: 120,
      originalPrice: 160,
      rating: 5,
      reviews: 88,
    },
    {
      id: 2,
      name: "AK-900 Wired Keyboard",
      image: keyboard,
      discount: "-35%",
      price: 960,
      originalPrice: 1160,
      rating: 4,
      reviews: 75,
    },
    {
      id: 3,
      name: "IPS LCD Gaming Monitor",
      image: monitor,
      discount: "-30%",
      price: 370,
      originalPrice: 400,
      rating: 5,
      reviews: 99,
    },
    {
      id: 4,
      name: "S-Series Comfort Chair",
      image: chair,
      discount: "-25%",
      price: 375,
      originalPrice: 400,
      rating: 4,
      reviews: 99,
    },
     {
       id: 5,
       name: "RTX 4070 Graphics Card",
       discount: "-20%",
       price: 400,
       originalPrice: 450,
       rating: 4,
       reviews: 99,
       image: graphiccard,
     },
     {
       id: 6,
       name: "Streaming Microphone Kit",
       discount: "-15%",
       price: 450,
       originalPrice: 500,
       rating: 4,
       reviews: 99,
       image: microphone,
     },
     {
       id: 7,
       name: "VR Headset Pro",
       discount: "-10%",
       price: 500,
       originalPrice: 530,
       rating: 4,
       reviews: 99,
       image: vrheadset,
     },
     {
       id: 8,
       name: "Gaming Router AX6000",
       discount: "-5%",
       price: 550,
       originalPrice: 600,
       rating: 4,
       reviews: 99,
       image: gamingrouter,
     },
  ];
export const products = [
  {
    id: 1,
    name: "The north coat",
    image: coat,
    currentPrice: 260,
    originalPrice: 360,
    rating: 5,
    reviews: 65,
    category: "Men's Fashion",
    subCategory: "Clothing", // Matches exactly with categoryData
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    image: buffledog,
    currentPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviews: 65,
    category: "Men's Fashion",
    subCategory: "Bags", // Matches exactly with categoryData
  },
  {
    id: 3,
    name: "Small BookSelf",
    image: bookshelf,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Home & Lifestyle",
    subCategory: "Furniture", // Matches exactly with categoryData
  },
  {
    id: 4,
    name: "All Black Formal Set",
    image: cloth1,
    currentPrice: 260,
    originalPrice: 360,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 5,
    name: "Blue Embroidered Kurta Set",
    image: cloth2,
    currentPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviews: 65,
    category: "Woman's Fashion", // Note the exact match
    subCategory: "Clothing",
  },
  {
    id: 6,
    name: "Aqua Blue  Cotton  Gown With Dupatta",
    image: cloth3,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 7,
    name: "Light Blue Puff Sleeve Top",
    image: cloth4,
    currentPrice: 260,
    originalPrice: 360,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 8,
    name: "Beige Button Collar Sweater",
    image: cloth5,
    currentPrice: 960,
    originalPrice: 1160,
    rating: 4.5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 9,
    name: "White Crop Top with Navy Skirt Set",
    image: cloth6,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 10,
    name: "Pastel Swirl Mini Dress",
    image: cloth7,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 10,
    name: "Floral Summer Midi Dress",
    image: cloth8,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 11,
    name: "Blue Paisley Slip Dress",
    image: cloth9,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Woman's Fashion",
    subCategory: "Clothing",
  },
  {
    id: 12,
    name: "Black shoe",
    image: shoe1,
    currentPrice: 360,
    originalPrice: null,
    rating: 5,
    reviews: 65,
    category: "Men's Fashion",
    subCategory: "Shoes",
  },

];


export  const exploreProducts = [
  {
    id: 1,
    name: "Breed Dry Dog Food",
    price: 100,
    rating: 3,
    reviews: 35,
    image: dogfood,
  },
  {
    id: 2,
    name: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviews: 95,
    image: camera,
    addToCart: true,
  },
  {
    id: 3,
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviews: 325,
    image: laptop,
  },
  {
    id: 4,
    name: "Curology Product Set",
    price: 500,
    rating: 4,
    reviews: 145,
    image: creame,
  },
  {
    id: 5,
    name: "Kids Electric Car",
    price: 960,
    rating: 5,
    reviews: 65,
    image: car,
    isNew: true,
    colors: ["black", "red"],
  },
  {
    id: 6,
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviews: 35,
    image: shoes,
    colors: ["yellow", "red"],
  },
  {
    id: 7,
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    rating: 4,
    reviews: 55,
    image: gamepad2,
    isNew: true,
    colors: ["black", "red"],
  },
  {
    id: 8,
    name: "Quilted Satin Jacket",
    price: 660,
    rating: 4,
    reviews: 55,
    image: jacket,
    colors: ["green", "red"],
  },
  {
    id: 9,
    name: "Quilted Satin Jacket",
    price: 660,
    rating: 4,
    reviews: 55,
    image: jacket,
    colors: ["green", "red"],
  },
  {
    id: 10,
    name: "Breed Dry Dog Food",
    price: 100,
    rating: 3,
    reviews: 35,
    image: dogfood,
  },
  {
    id: 11,
    name: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviews: 95,
    image: camera,
    addToCart: true,
  },
  {
    id: 12,
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviews: 325,
    image: laptop,
  },
  {
    id: 13,
    name: "Curology Product Set",
    price: 500,
    rating: 4,
    reviews: 145,
    image: creame,
  },
  {
    id: 14,
    name: "Kids Electric Car",
    price: 960,
    rating: 5,
    reviews: 65,
    image: car,
    isNew: true,
    colors: ["black", "red"],
  },
  {
    id: 15,
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviews: 35,
    image: shoes,
    colors: ["yellow", "red"],
  },
  {
    id: 16,
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    rating: 4,
    reviews: 55,
    image: gamepad2,
    isNew: true,
    colors: ["black", "red"],
  },
];